export const STORY_LIST_REQUEST = "STORY_LIST_REQUEST";
export const STORY_LIST_SUCCESS = "STORY_LIST_SUCCESS";
export const STORY_LIST_FAIL = "STORY_LIST_FAIL";

export const STORY_DETAIL_REQUEST = "STORY_DETAIL_REQUEST";
export const STORY_DETAIL_SUCCESS = "STORY_DETAIL_SUCCESS";
export const STORY_DETAIL_FAIL = "STORY_DETAIL_FAIL";
