export const STORY_LIST_REQUEST = "STORY_LIST_REQUEST";
export const STORY_LIST_SUCCESS = "STORY_LIST_SUCCESS";
export const STORY_LIST_FAIL = "STORY_LIST_FAIL";

export const STORY_DETAIL_REQUEST = "STORY_DETAIL_REQUEST";
export const STORY_DETAIL_SUCCESS = "STORY_DETAIL_SUCCESS";
export const STORY_DETAIL_FAIL = "STORY_DETAIL_FAIL";

export const STORY_CREATE_REQUEST = "STORY_CREATE_REQUEST";
export const STORY_CREATE_SUCCESS = "STORY_CREATE_SUCCESS";
export const STORY_CREATE_FAIL = "STORY_CREATE_FAIL";
export const STORY_CREATE_RESET = "STORY_CREATE_RESET";